### ISSUE TITLE
[Feature] Adding Scroll bar in the Preview window

### ISSUE THREAD

**Issue by ives-kp** [Webuddhist-tech/OpenPecha-Editors#16]
Please add the vertical scroll bar in the Preview window.

![image](https://user-images.githubusercontent.com/76642050/141750942-1616e285-5d36-436e-889a-f494d7ba4b02.png)

**Comment by ngawangtrinley** [comment]
@ives-kp please assign this to someone

**Comment by ives-kp** [comment]
@10zinten 
Hi Tenzin, would you please help to add the Scroll bar in Preview window.
Thank you

**Comment by 10zinten** [comment]
sure, I will fix it ASAP and let you know

**Comment by 10zinten** [comment]
@ives-kp fixed a484673b673e14452256b6f1a83a14d2be371170
