### ISSUE TITLE
[Test Case : D4213] parentheses-caused contents missing

### ISSUE THREAD

**Issue by ives-kp** [Webuddhist-tech/OpenPecha-Editors#25]
[Test Case]:D4213, P.10

The notes texts within parentheses will be discarded by the current མཆན་གྲངས་ detection mechanism.

![image](https://user-images.githubusercontent.com/76642050/146124092-d073e3a8-e89f-488e-ac77-070a41376914.jpeg)

![image](https://user-images.githubusercontent.com/76642050/146124103-13759a2e-7f43-4d51-af67-14c7a6a230df.jpeg)

https://user-images.githubusercontent.com/76642050/146124134-286f8265-4bea-4e47-ad1f-7261efa2932b.MOV

**Comment by kaldan007** [comment]
parantheses needs to be replaced by ⦇ and ⦈
