### ISSUE TITLE
[Test Case : D4213] Annotation missing at the beginning of sentences 

### ISSUE THREAD

**Issue by ives-kp** [Webuddhist-tech/OpenPecha-Editors#26]
[Test Case]: D4213, P.26; D4213, P.30

Annotations right in front of the sentences will be discarded. Please have a look at these. Thanks.

D4213, P.26
![D0C41ADB-FBAA-4887-9F91-6F733980FDED](https://user-images.githubusercontent.com/76642050/146126434-43adf47e-23f3-4f15-9ad9-fabc0b1c1480.jpeg)

D4213, P.30
![C734BD9B-8B36-4293-B01B-BC4B31E17067](https://user-images.githubusercontent.com/76642050/146126453-ad2d50be-fa45-4ea0-bb50-8414cd0a891d.jpeg)

**Comment by kaldan007** [comment]
exception has been handled.
